# GitLab CI/CD Pipeline - Mirror & Push to ECR
# Complete template for pulling upstream images and mirroring to AWS ECR

variables:
  # Upstream image configuration
  UPSTREAM_IMAGE: ghcr.io/beryju/gravity
  UPSTREAM_TAG: stable
  # ECR configuration
  ECR_REGISTRY: $ECR_AWS_ACCOUNT_ID.dkr.ecr.$ECR_AWS_REGION.amazonaws.com
  ECR_REPOSITORY: $ECR_REGISTRY/gravity

stages:
  - publish

# Push upstream image to AWS ECR on tag
publish:ecr:
  stage: publish
  image: quay.io/podman/stable:latest
  before_script:
    # Install AWS CLI
    - microdnf install -y python3 python3-pip
    - pip3 install awscli
    # Configure AWS credentials
    - export AWS_ACCESS_KEY_ID=${ECR_AWS_ACCESS_KEY_ID}
    - export AWS_SECRET_ACCESS_KEY=${ECR_AWS_SECRET_ACCESS_KEY}
    - export AWS_DEFAULT_REGION=${ECR_AWS_REGION}
    # Login to ECR
    - echo "Logging into AWS ECR..."
    - aws ecr get-login-password --region ${ECR_AWS_REGION} |
      podman login --username AWS --password-stdin ${ECR_AWS_ACCOUNT_ID}.dkr.ecr.${ECR_AWS_REGION}.amazonaws.com
  script:
    - VERSION=${CI_COMMIT_TAG#v}
    - echo "Pushing image to ECR ${ECR_REPOSITORY}:${VERSION}"

    # Pull upstream image
    - echo "Pulling upstream image..."
    - podman pull ${UPSTREAM_IMAGE}:${UPSTREAM_TAG}

    # Tag for ECR
    - echo "Tagging images..."
    - podman tag ${UPSTREAM_IMAGE}:${UPSTREAM_TAG} ${ECR_REPOSITORY}:${VERSION}
    - podman tag ${UPSTREAM_IMAGE}:${UPSTREAM_TAG} ${ECR_REPOSITORY}:latest

    # Push to ECR
    - echo "Pushing to ECR..."
    - podman push ${ECR_REPOSITORY}:${VERSION}
    - podman push ${ECR_REPOSITORY}:latest

    - echo "Image pushed successfully:"
    - echo "  ${ECR_REPOSITORY}:${VERSION}"
    - echo "  ${ECR_REPOSITORY}:latest"
  rules:
    - if: $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/
  tags:
    - shared
